name: srcities-slr-inputs
channels:
  - chrisroadmap
  - conda-forge
  - nodefaults
dependencies:
  - fair==1.6.2
  - climateforcing==0.3.0
  - h5py
  - jupyter
  - jupytext
  - matplotlib
  - netcdf4
  - numpy<2
  - pandas
  - scipy
  - tqdm
  - xarray
